apiVersion: v1
kind: Service
metadata:
  name: {{ include "yc-log-ui.fullname" . }}-frontend
  labels:
    {{- include "yc-log-ui.labels" . | nindent 4 }}-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.frontend }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "yc-log-ui.selectorLabels" . | nindent 4 }}-frontend
