apiVersion: v1
kind: Service
metadata:
  name: {{ include "yc-log-ui.fullname" . }}-backend
  labels:
    {{- include "yc-log-ui.labels" . | nindent 4 }}-backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.backend }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "yc-log-ui.selectorLabels" . | nindent 4 }}-backend
